// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXEXtPpwlHk8ZDGxp2eiJPDHbd6kkeDJI',
    appId: '1:810359951312:web:4b96d4d86e369fef1033d5',
    messagingSenderId: '810359951312',
    projectId: 'clone-uber-app-c21a1',
    authDomain: 'clone-uber-app-c21a1.firebaseapp.com',
    storageBucket: 'clone-uber-app-c21a1.firebasestorage.app',
    measurementId: 'G-LHWRLF13GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhCqTgFhGN6ChKEVrHRPma4fWMsmO-nMs',
    appId: '1:810359951312:android:6f31c9dcb952e92f1033d5',
    messagingSenderId: '810359951312',
    projectId: 'clone-uber-app-c21a1',
    storageBucket: 'clone-uber-app-c21a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4SxNlCgFQ2Gl_5j8FwF3BmiL8aEdVKLg',
    appId: '1:810359951312:ios:f9586947cccef17b1033d5',
    messagingSenderId: '810359951312',
    projectId: 'clone-uber-app-c21a1',
    storageBucket: 'clone-uber-app-c21a1.firebasestorage.app',
    iosClientId: '810359951312-l3mc24ebq1ohkkseekkscjnd583del7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.usersApp',
  );
}
